<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchBar</name>
   <tag></tag>
   <elementGuidId>a85c0b81-3791-4513-81c2-6873312604d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>055314a0-cb38-4985-98eb-b1f1e0fb6ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7147e5d3-4fbc-4c28-8f90-026679edd5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>c8c11aff-4477-47d3-be2f-95befe8b51d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search …</value>
      <webElementGuid>2991961e-6bbb-4dcd-8cd1-dc3fc0a9c5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>bc37f755-eb00-4b9d-8db0-c773262b2980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home page-template page-template-home page page-id-9 wp-custom-logo app-data index-data singular-data page-data page-9-data page-home-data home-data front-page-data elementor-default elementor-kit-7238&quot;]/header[@class=&quot;header header--normal&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;search-popup active&quot;]/div[@class=&quot;search__inner-wrapper&quot;]/form[@class=&quot;search-form&quot;]/label[1]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>ce59b03d-ee13-4c02-80d5-430a74876c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>c5088505-f7da-4cee-8eac-121704132f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fab0ef39-410f-45cb-865e-744f59ce32d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search …' and @name = 's']</value>
      <webElementGuid>ed934290-da37-4248-8b56-9ee70f4d37e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
