<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchButton</name>
   <tag></tag>
   <elementGuidId>996b3374-19ee-4ca8-9960-cba0adb76edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.search-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a007675-4f7f-4733-929a-812edc2268d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>63633516-c96a-4789-85c5-95fbdcc13f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-submit</value>
      <webElementGuid>fc802750-7c80-41bb-8b7d-263f02da84a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>755c9f5b-88ad-49da-a336-4fe01a6ab437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home page-template page-template-home page page-id-9 wp-custom-logo app-data index-data singular-data page-data page-9-data page-home-data home-data front-page-data elementor-default elementor-kit-7238&quot;]/header[@class=&quot;header header--normal&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;search-popup active&quot;]/div[@class=&quot;search__inner-wrapper&quot;]/form[@class=&quot;search-form&quot;]/input[@class=&quot;search-submit&quot;]</value>
      <webElementGuid>999675d4-d1fe-4d45-8488-459154022279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Search']</value>
      <webElementGuid>463fb2c5-9434-4125-98b5-741bc7166178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>e1fa4cf4-ef49-4eb9-9115-9c42c834e347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>38b3b501-b9de-4355-951d-f096f193c21c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
