<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select - Titanium Black  Titanium _12f0d4</name>
   <tag></tag>
   <elementGuidId>e5517ee6-4d14-4312-af32-9510d0573519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='x-msku__select-box-1000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#x-msku__select-box-1000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eaef997d-f552-4247-945c-4bc3d9a9a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-msku__select-box</value>
      <webElementGuid>3b81ac4f-06f4-4a40-ba73-ece4d46ca968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>x-msku__select-box-1000</value>
      <webElementGuid>fd2dafaf-587e-41a6-b22c-3af8872a104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5be42bf1-d040-4329-978b-7f78793ae668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selectboxid</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>4b33d408-2036-4b07-961e-71b63238873c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Please select a Color</value>
      <webElementGuid>dc917e44-a22e-45d7-af02-8819cdfebaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selectboxlabel</name>
      <type>Main</type>
      <value>Color</value>
      <webElementGuid>56d1e82b-dab5-49de-b969-ed6f2bf08c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select - Titanium Black  Titanium Gray  Titanium Violet   (Out Of Stock) Titanium Yellow </value>
      <webElementGuid>5a42e6f2-674e-473f-a27c-b9e73952a5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;x-msku__select-box-1000&quot;)</value>
      <webElementGuid>52dd83cc-bcd2-4bb8-8ed4-bf666a350f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='x-msku__select-box-1000']</value>
      <webElementGuid>b8fede50-3873-4b06-a704-7e7db00e0404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[7]/div/label/span[2]/select</value>
      <webElementGuid>18548ebb-166d-4eb1-8cda-9fc75cbb31ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>3039773e-2201-489c-b6d2-89fc8f0aac9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[5]/following::select[1]</value>
      <webElementGuid>a01f0c7e-9159-4239-a946-bbe016b80890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::select[1]</value>
      <webElementGuid>23cb0bb0-8164-4667-92df-21e14937416c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::select[1]</value>
      <webElementGuid>c7839562-8a96-413a-95ec-318925b70361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>da75a58f-7ce7-49ad-b56e-c85c879adcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'x-msku__select-box-1000' and (text() = '- Select - Titanium Black  Titanium Gray  Titanium Violet   (Out Of Stock) Titanium Yellow ' or . = '- Select - Titanium Black  Titanium Gray  Titanium Violet   (Out Of Stock) Titanium Yellow ')]</value>
      <webElementGuid>52a18864-543a-4a54-b36c-62f7dde97d4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
