<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Send</name>
   <tag></tag>
   <elementGuidId>07785967-32b1-4de0-a638-df5ce1a77081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='T-I J-J5-Ji aoO v7 T-I-atl L3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08de663e-d68b-4be4-9842-d4331f047cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:f2</value>
      <webElementGuid>40651c9e-7a48-4b2e-ae10-e61802b5160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>T-I J-J5-Ji aoO v7 T-I-atl L3 T-I-JW T-I-JO T-I-Zf-aw2</value>
      <webElementGuid>02b9fd28-14cf-4b7a-9b32-7d4877dfac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d93b65bc-5bf1-4b2b-808f-a4157ca08320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>60e91d7f-dc82-47ba-b66b-fef13ef2fa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Send ‪(Ctrl-Enter)‬</value>
      <webElementGuid>48ee48e5-700e-48d7-b38d-775b1c0bbad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Send ‪(Ctrl-Enter)‬</value>
      <webElementGuid>ec6a7414-a8d6-49c4-b5a0-7e6e46310b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip-delay</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>25ba45f4-6c42-403f-95bb-d23b10d2f264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>32601; u014N:xr6bB,cOuCgd,Kr2w4b; dYFj7e:true; 11:WyIjbXNnLWE6cjI3ODM4NTg2Mzk4MTI2NDA3MTgiLG51bGwsbnVsbCxudWxsLDEsbnVsbCxbIiN0aHJlYWQtYTpyNzM5MjkwODUyNzYwNTEzOTc4NiJdLDAsbnVsbCxudWxsLDAsbnVsbCwxLDAsWzEsMCwwXV0.; 4:W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsMV0.</value>
      <webElementGuid>57600920-5192-425a-80f3-eb31643fd07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>0ac0d87a-61d8-450e-924c-e2c0d73cfd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:f2&quot;)</value>
      <webElementGuid>b1261d39-63a0-4b7e-81bc-d66dc3c51193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':f2']</value>
      <webElementGuid>e3a9b6c0-0a99-4d66-a7e2-81392e03d15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':ha']/div[2]/div</value>
      <webElementGuid>6e0a872b-ce13-4092-97d8-ebc541cfd57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checking...'])[1]/following::div[7]</value>
      <webElementGuid>b29c8387-1d9d-4b3e-9d1a-8e6858777b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recheck'])[1]/following::div[10]</value>
      <webElementGuid>404d7e6e-e7c4-461c-b707-57694b1798c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule send'])[1]/preceding::div[59]</value>
      <webElementGuid>ef33d3e2-28d9-43c9-8f13-5b3d28de58a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snooze'])[1]/preceding::div[71]</value>
      <webElementGuid>f95d7c8a-6b30-4d30-bc11-ff9207d64368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>aa99b6d1-4a43-449f-a645-e82d4f8cd0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td/div/div[2]/div</value>
      <webElementGuid>bd962c50-9888-4bbe-a092-d23c47c072b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':f2' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>d09d6373-9e87-4736-ad39-bdf58fe6d2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
