<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automatic Test</name>
   <tag></tag>
   <elementGuidId>33bf1425-9d45-4f78-a02f-1aca6da29c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.aL8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b97a7c2a-be7d-4a07-9d3a-c48254e24d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aL8</value>
      <webElementGuid>d733cf02-60db-49fb-afe6-01c75556da00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-id</name>
      <type>Main</type>
      <value>automatic.test.example@gmail.com</value>
      <webElementGuid>779fba34-49b9-48ea-9c70-c2304b6bd7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Automatic Test</value>
      <webElementGuid>88783ebc-b999-4b29-b504-220ebb5260de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>322af839-2fea-4847-bb22-24a047b1cc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-owner-id</name>
      <type>Main</type>
      <value>116</value>
      <webElementGuid>4e0a16b4-a305-4c1e-bf47-1c4e65e7ce8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automatic Test</value>
      <webElementGuid>687f461c-eabd-4a79-b03d-3fe5e7c8e5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ky&quot;)/div[@class=&quot;agK&quot;]/div[@class=&quot;agB&quot;]/div[@class=&quot;agF&quot;]/div[@class=&quot;agE agG&quot;]/div[@class=&quot;aL8&quot;]</value>
      <webElementGuid>43abdd57-d7e1-4e47-86df-33ceda180383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':ky']/div/div[2]/div/div/div</value>
      <webElementGuid>02d82b92-a449-4d10-99f0-73cd5707d708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Word'])[1]/following::div[24]</value>
      <webElementGuid>e086272e-c6fd-44a3-99b8-d96077c9f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ignore'])[1]/following::div[26]</value>
      <webElementGuid>09f23bc0-6126-4607-b28f-8973cd96d40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automatic']/parent::*</value>
      <webElementGuid>e6f9001f-159d-4183-b97e-19c30f3f8a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div[2]/div/div/div</value>
      <webElementGuid>93276a67-b659-4439-a620-b921f578228d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Automatic Test' or . = 'Automatic Test')]</value>
      <webElementGuid>5f38e92f-56a6-4518-8c36-29a2467c7379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
