<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Compose</name>
   <tag></tag>
   <elementGuidId>6793bad8-c13b-409b-9cea-3feb37d503b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Send feedback to Google'])[1]/following::div[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.T-I.T-I-KE.L3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>183f7940-c8ae-4b3e-83bb-2cd0e8a05a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>T-I T-I-KE L3</value>
      <webElementGuid>38f99dd6-fca5-41af-b77b-4359efd258f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f384c6b8-a749-418b-aa99-7d188ef16c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec10decc-1344-4ed4-b241-1fa856f7ced2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>eIu7Db</value>
      <webElementGuid>5331191c-7b02-4289-a951-a345d8360a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>click:dlrqf; clickmod:dlrqf</value>
      <webElementGuid>20a4a33c-e5e6-4436-a7da-dae5aedec847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>20510; u014N:cOuCgd,Kr2w4b</value>
      <webElementGuid>7f7b8062-1f44-4c07-97e4-737341839d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gh</name>
      <type>Main</type>
      <value>cm</value>
      <webElementGuid>e74ea33c-5409-4029-bdaa-aa606de9bb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compose</value>
      <webElementGuid>08a06c84-b940-4921-9965-5b15561cb9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;aAX&quot;]/body[@class=&quot;aAU&quot;]/div[7]/div[@class=&quot;nH&quot;]/div[@class=&quot;nH&quot;]/div[@class=&quot;nH aqk aql bkL&quot;]/div[@class=&quot;aeN WR baA nH oy8Mbf&quot;]/div[@class=&quot;aic&quot;]/div[@class=&quot;z0&quot;]/div[@class=&quot;T-I T-I-KE L3&quot;]</value>
      <webElementGuid>0a7e820d-18ca-4735-843a-df8d8d8bacea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send feedback to Google'])[1]/following::div[34]</value>
      <webElementGuid>6c0b7347-be4a-4957-b150-7fad17266093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updates'])[1]/following::div[36]</value>
      <webElementGuid>738a944a-ed4c-45f0-876d-e735ffd73128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[1]/preceding::div[2]</value>
      <webElementGuid>40dc1321-bb37-41ac-80bb-1ff3443c0543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/preceding::div[3]</value>
      <webElementGuid>57231b20-307c-4c1e-87e1-1e294d933367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compose']/parent::*</value>
      <webElementGuid>701e1973-6c7b-4ae9-b98a-a82bcce040b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>8f821833-bb8b-4423-9371-fde6044f6e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Compose' or . = 'Compose')]</value>
      <webElementGuid>d8563ab4-5a2e-4f36-896f-c35822c618d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
