import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 13-velj-2024 02:18:11 PM'
'File path: C:\\Users\\lfilipovic\\Desktop\\KatalonStudioMigration.side'
'Generated by: null'
'----------------------------------------------------'

String baseUrl = "https://opensource-demo.orangehrmlive.com"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /web/index.php/auth/login |  | "
selenium.open("/web/index.php/auth/login", "")

"setWindowSize | 1392x1104 |  | "
// Method setWindowSize is not supported

"click | name=username |  | "
selenium.click("name=username")

"type | name=username | Admin | "
selenium.type("name=username", "Admin")

"click | name=password |  | "
selenium.click("name=password")

"type | name=password | admin123 | "
selenium.type("name=password", "admin123")

"click | css=.oxd-button |  | "
selenium.click("css=.oxd-button")

"click | css=.oxd-main-menu-item-wrapper:nth-child(9) .oxd-text |  | "
selenium.click("css=.oxd-main-menu-item-wrapper:nth-child(9) .oxd-text")

"click | css=.oxd-select-text--focus > .oxd-select-text-input |  | "
selenium.click("css=.oxd-select-text--focus > .oxd-select-text-input")

"mouseUp | css=.orangehrm-horizontal-padding |  | "
selenium.mouseUp("css=.orangehrm-horizontal-padding")

"close |  |  | "
selenium.close()
