<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to cart</name>
   <tag></tag>
   <elementGuidId>32ccb308-40e6-4efe-9289-0b0e12fe1b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContent']/div/div[9]/ul/li[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vim.x-atc-action.overlay-placeholder > a.ux-call-to-action.fake-btn.fake-btn--fluid.fake-btn--large.fake-btn--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8546554f-36c4-4034-9dd6-046609b36312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ux-call-to-action</value>
      <webElementGuid>74330fd5-9cfc-4d65-846b-f5fe72f18065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>fbc63bca-1c80-4ab8-832f-b8afc337d819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_sp</name>
      <type>Main</type>
      <value>p4429486.l1473</value>
      <webElementGuid>d3fc1103-84e7-48da-8595-23ef32edc334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-viewport</name>
      <type>Main</type>
      <value>{&quot;trackableId&quot;:&quot;01HP4H0YZAKW55PZS7HXJCMZD6&quot;}</value>
      <webElementGuid>8bdacbf1-b564-479f-b14a-b131ad096fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ux-call-to-action fake-btn fake-btn--fluid fake-btn--large fake-btn--primary</value>
      <webElementGuid>9261f1c2-55d9-4663-9b33-eafab91768af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>afcb22e7-1c00-453b-aec5-004512dadd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>964cbdb9-ae64-4928-8e55-0f334838a9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;vim d-vi-evo-region&quot;]/div[@class=&quot;vim vi-evo-row-gap&quot;]/ul[@class=&quot;x-buybox-cta mar-t-20&quot;]/li[2]/div[@class=&quot;vim x-atc-action overlay-placeholder&quot;]/a[@class=&quot;ux-call-to-action fake-btn fake-btn--fluid fake-btn--large fake-btn--primary&quot;]</value>
      <webElementGuid>53890edd-4c5b-4890-9f45-2ac0dc4e7ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[9]/ul/li[2]/div/a</value>
      <webElementGuid>36ef8d87-40a8-4227-bb35-209d9c62fc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out as guest'])[1]/following::a[1]</value>
      <webElementGuid>e60bb2eb-dc18-4252-b740-fc786d43dd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to check out'])[1]/following::a[2]</value>
      <webElementGuid>8e2f3df1-ba86-41cf-8a7f-3ee05b879f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to watchlist'])[1]/preceding::a[1]</value>
      <webElementGuid>fbd2b127-be39-4add-a3ec-764c490a8f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>6c656f95-8de5-4265-8dc6-46b45ae2d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>d56cafe9-adbb-4f03-892c-86f0c8a1f517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>0acbee5a-22dc-4192-a22b-65a65d691378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
